apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway
data:
  application.yaml: |-
    spring:
      cloud:
        gateway:
          mvc:
            routes:
              - id: user-service
                uri: lb://user-service
                predicates:
                  - Path=/user-service/**
