apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: spring-cloud-kubernetes-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "endpoints", "pods", "services"]
    verbs: ["get", "list", "watch"]