spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/user-service/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    enabled: true
