server:
  port: 8883
message:
  from: configserver
master:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-k8s-master
    username: root
    password: Mysql8@admin
    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  flyway:
    enabled: false