apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-service
  labels:
    app: sales-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-service
  template:
    metadata:
      labels:
        app: sales-service
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: sales-service
          image: sales-service
          ports:
            - containerPort: 8881
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: development
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED # (3)
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI # (4)
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
spec:
  selector:
    app: sales-service
  ports:
    - protocol: TCP
      port: 8881
      targetPort: 8881
  type: LoadBalancer