spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:8888  # Configuration for non-Kubernetes (default profile)
    activate:
      on-profile: local
server:
  servlet:
    context-path: /user-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    enabled: true