apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
data:
  application.yaml: |-
    server:
      port: 8882
    message:
      from: kubernetes-configmap

    master:
      datasource:
        url: jdbc:mysql://mysql:3306/spring-k8s-master
        username: root
        password: Mysql8@admin
        driver-class-name: com.mysql.cj.jdbc.Driver
    tenant:
      datasource:
        driver-class-name:
          mysql: com.mysql.cj.jdbc.Driver
          postgresql: org.postgresql.Driver
    keycloak:
      url: http://ec2-13-201-193-82.ap-south-1.compute.amazonaws.com:8080/
      clientId: ims-app
      clientSecret: AhAVPFgp3KVk0htn1e8I4e9aaSnQO1gO
    spring:
      flyway:
        enabled: false
      kafka:
        consumer:
          bootstrap-servers: ec2-13-201-193-82.ap-south-1.compute.amazonaws.com:9092
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          auto-offset-reset: earliest
          group-id: user-service
          properties:
            spring:
              json:
                trusted:
                  packages: "*"
    encryption:
      private-key: ${PRIVATE_KEY}