apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: user-service
      docker:
        dockerfile: Dockerfile
  local: {}

deploy:
  kubectl:
    manifests:
      - config.yaml
      - deployment.yaml