apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-service
data:
  application.yaml: |-
    server:
      port: 8883
    message:
      from: kubernetes-configmap
    master:
      datasource:
        url: jdbc:mysql://mysql:3306/spring-k8s-master
        username: root
        password: Mysql8@admin
        driver-class-name: com.mysql.cj.jdbc.Driver
    tenant:
      datasource:
        driver-class-name:
          mysql: com.mysql.cj.jdbc.Driver
          postgresql: org.postgresql.Driver
    spring:
      flyway:
        enabled: false
      kafka:
        producer:
          bootstrap-servers: ec2-13-201-193-82.ap-south-1.compute.amazonaws.com:9092
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    encryption:
      private-key: ${PRIVATE_KEY}